# Requirement Addressed: Dependency Management Automation
# Location: Technical Specification/9.5 Development & Deployment/9.5.2 CI/CD Pipeline
# Description: Automates dependency updates for both backend and frontend components

# Requirement Addressed: Security and Stability
# Location: Technical Specification/7.4 Cross-Cutting Concerns/7.4.2 Security Architecture
# Description: Ensures dependencies are kept up-to-date with security patches

version: 2
updates:
  # Backend Python dependencies using pip
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    reviewers:
      - "Development Team"
    groups:
      python-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Frontend JavaScript dependencies using npm
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"
      - "javascript"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    reviewers:
      - "Development Team"
    groups:
      javascript-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    open-pull-requests-limit: 5
    reviewers:
      - "Development Team"