/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation" />

// Requirement: Frontend TypeScript Configuration (9.2 Frameworks & Libraries/9.2.1 Core Frameworks)
// This file is automatically generated and should not be edited manually.
// It ensures compatibility with Next.js-specific TypeScript settings.

// Declare global types for images
declare module '*.png' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.jpg' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.jpeg' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.gif' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.webp' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.avif' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.ico' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

declare module '*.bmp' {
  const content: import('../node_modules/next/dist/shared/lib/image-external').StaticImageData
  export default content
}

// Declare global types for SVG
declare module '*.svg' {
  const content: React.FunctionComponent<React.SVGProps<SVGSVGElement>>
  export default content
}

// Augment the NodeJS namespace for Next.js environment variables
declare namespace NodeJS {
  interface ProcessEnv {
    readonly NODE_ENV: 'development' | 'production' | 'test'
    readonly REACT_APP_API_BASE_URL: string
    readonly REACT_APP_AUTH_CLIENT_ID: string
    readonly REACT_APP_ANALYTICS_KEY: string
  }
}

// Augment the window object for Next.js runtime configuration
interface Window {
  // Add any custom window properties needed for the application
  __NEXT_DATA__: any
}